---
title: "Training"
author: "VCT Kevin Oliver"
date: "8/2/2018"
output: html_document
---

Include the needed library

```{r}
library(ggplot2)
library(cowplot)
library(randomForest)
library(party)
library(caret)
```

Read some data from the train set
```{r}
train <- read.csv("train.csv", header = TRUE)
test <- read.csv("test.csv", header = TRUE)
summary(train)
```
Check out the structure of the object
```{r}
str(train)
```

Check out the unique value of each objects
```{r}
apply(train, 2, function(x) length(unique(x)))
```
With the summary of the data, we use random forest algorithm to generate a model. First we seperate the train data set into two parts, first a training parts and a test part for testing the acuraccy of the different trees.
```{r}

set.seed(123)
ind <- sample(2, nrow(train), replace = TRUE, prob = c(0.7,0.3))
trainSet <- train[ind == 1,]
testSet <- train[ind == 2,]

set.seed(42)
trainSet.imputed <- rfImpute(SalePrice~., data = trainSet, iter = 6)
set.seed(222)
rf <- randomForest(SalePrice~., data = trainSet.imputed)
rf

```